"""
CI helpers for SbtDeskTran releases.

Typical CI flow:
  python ci_release.py set-version v2026.07.07.8
  python ci_release.py ensure-changes v2026.07.07.8 --commit
  python -m PyInstaller ...
  python ci_release.py assets v2026.07.07.8
"""
import argparse
import datetime as dt
import os
import pathlib
import re
import shutil
import subprocess
import sys
import zipfile


APP_EXE_NAME = "SbtDeskTran.exe"
DIST_DIR = pathlib.Path("dist")
VERSION_FILE = pathlib.Path("version.py")
VERSION_CHANGES = pathlib.Path("version_changes.txt")
VERSION_CHANGES_PLACEHOLDERS = {
    "",
    "SbtDeskTran version changes",
    "SbtDeskTran version changes\n\nKeep release/change details here instead of putting them in the release body.",
}


def normalize_version(value: str) -> str:
    raw = (value or "").strip()
    match = re.search(r"\bv?(\d+(?:\.\d+)+)\b", raw)
    if not match:
        raise SystemExit(
            "Release version must contain a numeric tag like v2026.07.07.8"
        )
    return match.group(1)


def version_arg(value: str = "") -> str:
    return normalize_version(value or os.environ.get("RELEASE_VERSION") or os.environ.get("GITHUB_REF_NAME", ""))


def run_git(*args: str, check: bool = True) -> str:
    result = subprocess.run(
        ["git", *args],
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if check and result.returncode != 0:
        raise SystemExit(result.stderr.strip() or f"git {' '.join(args)} failed")
    return result.stdout.strip()


def git_success(*args: str) -> bool:
    return subprocess.run(["git", *args], check=False).returncode == 0


def set_version(version: str) -> None:
    VERSION_FILE.write_text(
        '# Auto-generated by CI/CD - do not edit manually\n'
        f'__version__ = "{version}"\n',
        encoding="utf-8",
    )


def previous_release_ref() -> str:
    ref = run_git("describe", "--tags", "--abbrev=0", "--match", "v*", "HEAD^", check=False)
    if ref:
        return ref
    return run_git("rev-list", "--max-parents=0", "HEAD")


def file_at_ref(ref: str, path: pathlib.Path) -> str:
    return run_git("show", f"{ref}:{path.as_posix()}", check=False)


def current_changes_text() -> str:
    if not VERSION_CHANGES.exists():
        return ""
    return VERSION_CHANGES.read_text(encoding="utf-8").strip()


def is_placeholder_changes(text: str) -> bool:
    normalized = re.sub(r"\s+", " ", (text or "").strip())
    return any(normalized == re.sub(r"\s+", " ", item.strip()) for item in VERSION_CHANGES_PLACEHOLDERS)


def change_summary(base_ref: str) -> str:
    commits = run_git("log", "--oneline", f"{base_ref}..HEAD", check=False).splitlines()
    files = run_git("diff", "--name-only", f"{base_ref}..HEAD", check=False).splitlines()

    lines = ["Commits:"]
    lines.extend(f"- {line}" for line in commits[:30])
    if not commits:
        lines.append("- No commit summary available")

    lines.append("")
    lines.append("Changed files:")
    lines.extend(f"- {line}" for line in files[:50])
    if not files:
        lines.append("- No changed file summary available")
    return "\n".join(lines)


def ensure_version_changes(version: str, base_ref: str = "") -> bool:
    base_ref = base_ref or previous_release_ref()
    before = file_at_ref(base_ref, VERSION_CHANGES).strip()
    current = current_changes_text()

    if current and current != before and not is_placeholder_changes(current):
        return False

    today = dt.date.today().isoformat()
    existing = "" if is_placeholder_changes(current) else current
    existing = existing or "SbtDeskTran version changes"
    section = (
        f"\n\n## v{version} - {today}\n\n"
        "Auto-generated because version_changes.txt had no manual changes since "
        f"{base_ref}.\n\n"
        f"{change_summary(base_ref)}\n"
    )
    VERSION_CHANGES.write_text(existing.rstrip() + section, encoding="utf-8")
    return True


def commit_version_changes(version: str, push: bool) -> None:
    run_git("add", VERSION_CHANGES.as_posix())
    if not git_success("diff", "--cached", "--quiet"):
        run_git("commit", "-m", f"Update version changes for v{version}")
        if push:
            run_git("push")


def create_assets(version: str) -> None:
    DIST_DIR.mkdir(exist_ok=True)
    exe_path = DIST_DIR / APP_EXE_NAME
    if not exe_path.exists():
        raise SystemExit(f"Missing build output: {exe_path}")

    for stale_name in ("latest.json", "release_notes.txt"):
        stale_path = DIST_DIR / stale_name
        if stale_path.exists():
            stale_path.unlink()

    zip_path = DIST_DIR / f"SbtDeskTran-{version}.zip"
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.write(exe_path, APP_EXE_NAME)

    changes_out = DIST_DIR / "version_changes.txt"
    if VERSION_CHANGES.exists():
        shutil.copyfile(VERSION_CHANGES, changes_out)
    else:
        changes_out.write_text("SbtDeskTran version changes\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)

    set_version_parser = subparsers.add_parser("set-version")
    set_version_parser.add_argument("version", nargs="?")

    ensure_parser = subparsers.add_parser("ensure-changes")
    ensure_parser.add_argument("version", nargs="?")
    ensure_parser.add_argument("--base", default="")
    ensure_parser.add_argument("--commit", action="store_true")
    ensure_parser.add_argument("--push", action="store_true")

    assets_parser = subparsers.add_parser("assets")
    assets_parser.add_argument("version", nargs="?")

    args = parser.parse_args()

    if args.command == "set-version":
        set_version(version_arg(args.version))
    elif args.command == "ensure-changes":
        version = version_arg(args.version)
        changed = ensure_version_changes(version, args.base)
        if changed and args.commit:
            commit_version_changes(version, args.push)
        print("version_changes=updated" if changed else "version_changes=manual")
    elif args.command == "assets":
        create_assets(version_arg(args.version))
    else:
        sys.exit(2)


if __name__ == "__main__":
    main()
