<script lang="ts">
  import { invoke } from "@tauri-apps/api/core";
  import { open, save as saveDialog } from "@tauri-apps/plugin-dialog";
  type Entry={id:string;sourceLang:string;targetLang:string;sourceText:string;translation:string;status:string;updatedAt:string};
  let {onclose}:{onclose:()=>void}=$props(); let entries=$state<Entry[]>([]); let id=$state<string|null>(null); let sourceLang=$state("ja"); let targetLang=$state("vi"); let sourceText=$state(""); let translation=$state(""); let message=$state("");
  async function load(){try{entries=await invoke<Entry[]>("list_dictionary_entries")}catch(e){message=String(e)}} void load();
  function edit(item:Entry){id=item.id;sourceLang=item.sourceLang;targetLang=item.targetLang;sourceText=item.sourceText;translation=item.translation}
  function clear(){id=null;sourceText="";translation=""}
  async function save(){try{entries=await invoke<Entry[]>("save_dictionary_entry",{entry:{id,sourceLang,targetLang,sourceText,translation}});clear();message=""}catch(e){message=String(e)}}
  async function remove(item:Entry){try{entries=await invoke<Entry[]>("delete_dictionary_entry",{id:item.id});if(id===item.id)clear()}catch(e){message=String(e)}}
  async function importCsv(){const path=await open({multiple:false,filters:[{name:"CSV",extensions:["csv"]}]});if(typeof path!=="string")return;try{entries=await invoke<Entry[]>("import_dictionary_csv",{path});message=`Imported dictionary (${entries.length} total).`}catch(e){message=String(e)}}
  async function exportCsv(){const path=await saveDialog({defaultPath:"dictionary.csv",filters:[{name:"CSV",extensions:["csv"]}]});if(!path)return;try{const count=await invoke<number>("export_dictionary_csv",{path});message=`Exported ${count} entries.`}catch(e){message=String(e)}}
</script>
<div class="overlay" role="presentation" onclick={onclose}><div class="dialog" role="dialog" aria-modal="true" aria-labelledby="dict-title" tabindex="-1" onclick={e=>e.stopPropagation()} onkeydown={()=>{}}>
  <header><h2 id="dict-title">Dictionary</h2><div><button onclick={importCsv}>Import CSV</button><button onclick={exportCsv}>Export CSV</button><button class="close" onclick={onclose} aria-label="Close">×</button></div></header>
  <main><div class="form"><select bind:value={sourceLang}><option value="ja">Japanese</option><option value="vi">Vietnamese</option></select><span>→</span><select bind:value={targetLang}><option value="vi">Vietnamese</option><option value="ja">Japanese</option></select><input bind:value={sourceText} placeholder="Source term"/><input bind:value={translation} placeholder="Approved translation"/><button class="primary" onclick={save} disabled={!sourceText.trim()||!translation.trim()}>{id?"Update":"Add"}</button>{#if id}<button onclick={clear}>Cancel</button>{/if}</div>
  {#if message}<p class="message">{message}</p>{/if}<div class="list">{#each entries as item}<div class="item"><div><strong>{item.sourceText}</strong><span>{item.sourceLang} → {item.targetLang}</span></div><div class="translated">{item.translation}</div><button onclick={()=>edit(item)}>Edit</button><button onclick={()=>remove(item)}>Delete</button></div>{/each}{#if !entries.length}<p class="empty">No dictionary entries yet.</p>{/if}</div></main>
</div></div>
<style>
.overlay{position:fixed;inset:0;z-index:1600;display:grid;place-items:center;padding:12px;background:rgba(0,0,0,.55)}.dialog{width:min(780px,calc(100vw - 24px));max-height:calc(100vh - 24px);display:flex;flex-direction:column;color:var(--fg);background:var(--bg3);border:1px solid var(--border);border-top:3px solid var(--accent);border-radius:8px}header{display:flex;justify-content:space-between;align-items:center;padding:13px 16px;border-bottom:1px solid var(--border)}header div{display:flex;gap:6px}h2,p{margin:0}h2{font-size:15px}button,input,select{height:28px;border:1px solid var(--border);border-radius:3px;background:var(--combo-bg);color:var(--fg);font:inherit;font-size:11px;padding:0 8px}button{cursor:pointer}.close{border:0;background:transparent;font-size:22px}main{min-height:0;padding:14px;overflow:auto}.form{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.form input{flex:1;min-width:150px}.primary{color:var(--bg);border-color:var(--accent);background:var(--accent)}.list{display:grid;gap:5px;margin-top:14px}.item{display:grid;grid-template-columns:minmax(130px,1fr) minmax(150px,1.5fr) auto auto;align-items:center;gap:8px;padding:8px;background:var(--bg2);border:1px solid var(--border);border-radius:4px}.item strong,.item span{display:block}.item span,.empty{color:var(--fg2);font-size:10px}.translated{font-size:12px}.message{margin-top:9px;color:var(--accent);font-size:11px}@media(max-width:600px){.item{grid-template-columns:1fr auto auto}.translated{grid-column:1/-1;grid-row:2}}
</style>
