<script lang="ts">
  import { invoke } from "@tauri-apps/api/core";
  import { listen } from "@tauri-apps/api/event";
  import { open, save } from "@tauri-apps/plugin-dialog";
  import { onMount } from "svelte";
  type Progress={phase:string;completed:number;total:number;translated:number;skipped:number;failed:number};
  type Result={outputPath:string;scanned:number;translated:number;skipped:number;uniqueTexts:number;failed:number;errors:string[];logPath:string};
  type WorkbookInfo={sheets:string[];cells:number};
  let {engines,defaultEngine,onclose}:{engines:string[];defaultEngine:string;onclose:()=>void}=$props();
  let inputPath=$state("");let outputPath=$state("");let engine=$state("Google Translate");let sourceLang=$state("ja");let targetLang=$state("vi");
  let skipFormulas=$state(true);let skipProductCodes=$state(true);let sheets=$state<string[]>([]);let excludedSheets=$state<string[]>([]);let excludedColumns=$state("");let excludedRanges=$state("");let workbookCells=$state(0);
  let running=$state(false);let progress=$state<Progress>({phase:"ready",completed:0,total:0,translated:0,skipped:0,failed:0});let error=$state("");let result=$state<Result|null>(null);let taskId=$state("");let resumeAvailable=$state(false);
  onMount(()=>{engine=defaultEngine});
  function suggestedOutput(path:string){const dot=path.toLowerCase().lastIndexOf(".xlsx");return dot>=0?`${path.slice(0,dot)}_${targetLang}.xlsx`:`${path}_${targetLang}.xlsx`}
  async function detectResume(){try{resumeAvailable=Boolean(outputPath)&&await invoke<boolean>("has_excel_translation_checkpoint",{outputPath})}catch{resumeAvailable=false}}
  async function chooseInput(){const selected=await open({multiple:false,filters:[{name:"Excel Workbook",extensions:["xlsx"]}]});if(typeof selected!=="string")return;inputPath=selected;outputPath=suggestedOutput(selected);excludedSheets=[];result=null;error="";resumeAvailable=false;try{const info=await invoke<WorkbookInfo>("inspect_excel_file",{path:selected});sheets=info.sheets;workbookCells=info.cells;await detectResume()}catch(reason){error=String(reason);sheets=[]}}
  async function chooseOutput(){const selected=await save({defaultPath:outputPath||undefined,filters:[{name:"Excel Workbook",extensions:["xlsx"]}]});if(selected){outputPath=selected;await detectResume()}}
  function swap(){const next=sourceLang;sourceLang=targetLang;targetLang=next;if(inputPath)outputPath=suggestedOutput(inputPath)}
  function toggleSheet(sheet:string,excluded:boolean){excludedSheets=excluded?[...excludedSheets,sheet]:excludedSheets.filter(item=>item!==sheet)}
  async function start(){if(!inputPath||!outputPath){error="Select both input and output files.";return}running=true;error="";result=null;taskId=`${Date.now()}-${Math.random().toString(36).slice(2)}`;const unlisten=await listen<Progress>("translation-file-progress",event=>progress=event.payload);try{result=await invoke<Result>("translate_excel_file",{request:{taskId,inputPath,outputPath,sourceLang,targetLang,engine,skipFormulas,skipProductCodes,excludedSheets,excludedColumns:excludedColumns.split(",").map(v=>v.trim()).filter(Boolean),excludedRanges:excludedRanges.split(",").map(v=>v.trim()).filter(Boolean)}});resumeAvailable=false}catch(reason){error=String(reason);resumeAvailable=error.includes("Resume")||error.includes("checkpoint")}finally{unlisten();running=false}}
  async function cancel(){if(taskId)await invoke("cancel_excel_translation",{taskId})}
  async function openOutput(){if(result)await invoke("open_excel_output_location",{path:result.outputPath})}
</script>
<div class="overlay" role="presentation" onclick={()=>!running&&onclose()}><div class="dialog" role="dialog" aria-modal="true" aria-labelledby="file-trans-title" tabindex="-1" onclick={event=>event.stopPropagation()} onkeydown={()=>{}}>
  <header><div><h2 id="file-trans-title">Translate Excel File</h2><p>Creates a new workbook and never overwrites the source.</p></div><button class="close" onclick={onclose} disabled={running} aria-label="Close">×</button></header>
  <main>
    <label>Input workbook<div class="path"><input readonly value={inputPath} placeholder="Select an .xlsx file"/><button onclick={chooseInput} disabled={running}>Browse...</button></div></label>
    <label>Output workbook<div class="path"><input readonly value={outputPath} placeholder="Choose output file"/><button onclick={chooseOutput} disabled={running}>Browse...</button></div></label>
    <div class="row"><label>Engine<select bind:value={engine} disabled={running}>{#each engines as item}<option value={item}>{item}</option>{/each}</select></label><label>From<select bind:value={sourceLang} disabled={running}><option value="ja">Japanese</option><option value="vi">Vietnamese</option></select></label><button class="swap" onclick={swap} disabled={running}>Swap</button><label>To<select bind:value={targetLang} disabled={running}><option value="vi">Vietnamese</option><option value="ja">Japanese</option></select></label></div>
    <div class="checks"><label><input type="checkbox" bind:checked={skipFormulas} disabled={running}/> Skip formulas</label><label><input type="checkbox" bind:checked={skipProductCodes} disabled={running}/> Skip product codes</label></div>
    {#if sheets.length}<fieldset><legend>Sheets ({workbookCells} populated cells)</legend><div class="sheet-list">{#each sheets as sheet}<label><input type="checkbox" checked={!excludedSheets.includes(sheet)} onchange={event=>toggleSheet(sheet,!event.currentTarget.checked)} disabled={running}/>{sheet}</label>{/each}</div></fieldset>{/if}
    <label>Excluded columns<input bind:value={excludedColumns} placeholder="Example: A, C, AA" disabled={running}/></label>
    <label>Excluded ranges<input bind:value={excludedRanges} placeholder="Example: A1:D20, Sheet2!F:F, 'Sales Data'!2:5" disabled={running}/><small>Separate ranges with commas. A range without a sheet name applies to every selected sheet.</small></label>
    {#if running}<div class="progress"><div><span>{progress.phase}</span><span>{progress.completed}/{progress.total}</span></div><progress max={Math.max(1,progress.total)} value={progress.completed}></progress><small>{progress.translated} translated · {progress.skipped} skipped · {progress.failed} failed</small></div>{/if}
    {#if result}<div class="result"><strong>Completed</strong><span>{result.translated} cells translated · {result.failed} failed · {result.skipped} skipped</span><code>{result.outputPath}</code><div class="result-actions"><button onclick={openOutput}>Open output folder</button><span>Log: {result.logPath}</span></div>{#if result.errors.length}<details><summary>Cell errors ({result.errors.length})</summary>{#each result.errors as item}<div>{item}</div>{/each}</details>{/if}</div>{/if}
    {#if error}<p class="error">{error}</p>{/if}
    {#if resumeAvailable}<p class="resume-note">Completed batches were saved. Resume will skip them automatically.</p>{/if}
  </main>
  <footer>{#if running}<button onclick={cancel}>Cancel</button>{:else}<button onclick={onclose}>Close</button>{/if}<button class="primary" onclick={start} disabled={running||!inputPath||!outputPath}>{running?"Translating...":resumeAvailable?"Resume":"Translate"}</button></footer>
</div></div>
<style>
.overlay{position:fixed;inset:0;z-index:1600;display:grid;place-items:center;padding:12px;background:rgba(0,0,0,.55)}.dialog{width:min(680px,calc(100vw - 24px));max-height:calc(100vh - 24px);display:flex;flex-direction:column;color:var(--fg);background:var(--bg3);border:1px solid var(--border);border-top:3px solid var(--accent);border-radius:8px;box-shadow:0 16px 48px rgba(0,0,0,.48)}header{display:flex;justify-content:space-between;padding:14px 16px;border-bottom:1px solid var(--border)}h2,p{margin:0}h2{font-size:15px}header p{margin-top:4px;color:var(--fg2);font-size:11px}.close{border:0;background:transparent;font-size:22px}main{display:grid;gap:13px;padding:16px;overflow:auto}label{display:grid;gap:5px;color:var(--fg2);font-size:11px}label small{font-size:10px}.path,.row,.checks{display:flex;align-items:end;gap:7px}.path input{flex:1}.row label{flex:1}.swap{margin-bottom:1px}.checks label,.sheet-list label{display:flex;align-items:center;gap:5px;color:var(--fg)}input,select,button{height:29px;box-sizing:border-box;border:1px solid var(--border);border-radius:3px;background:var(--combo-bg);color:var(--fg);font:inherit;font-size:11px;padding:0 8px}button{cursor:pointer}input[type="checkbox"]{height:auto}fieldset{margin:0;padding:8px;border:1px solid var(--border);border-radius:4px}legend{color:var(--fg2);font-size:11px}.sheet-list{display:flex;flex-wrap:wrap;gap:7px 14px;max-height:90px;overflow:auto}.progress,.result{display:grid;gap:5px}.progress>div{display:flex;justify-content:space-between;font-size:11px}.progress progress{width:100%;height:8px}.progress small,.result span{color:var(--fg2);font-size:11px}.result{padding:9px;background:var(--bg2);border:1px solid var(--border);border-radius:4px}.result code{font-size:10px;overflow-wrap:anywhere}.result-actions{display:flex;align-items:center;gap:8px;min-width:0}.result-actions span{overflow-wrap:anywhere}.result details{font-size:11px;color:var(--warning)}.error{color:var(--error);font-size:11px}.resume-note{color:var(--warning);font-size:11px}footer{display:flex;justify-content:flex-end;gap:7px;padding:12px 16px;border-top:1px solid var(--border)}.primary{color:var(--bg);border-color:var(--accent);background:var(--accent)}button:disabled{opacity:.55;cursor:default}
</style>
